//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animals
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalPath
    {
        public int ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry CurrLocation { get; set; }
        public Nullable<int> TimeStep { get; set; }
        public Nullable<int> AnimalID { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
