//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModularSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_move
    {
        public int ID { get; set; }
        public Nullable<double> MVL { get; set; }
        public Nullable<long> MSL { get; set; }
        public Nullable<double> ENERGYUSED { get; set; }
        public Nullable<double> CROSSING { get; set; }
        public Nullable<double> PR_X { get; set; }
        public string LABEL { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    }
}
