//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModularSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_food
    {
        public int ID { get; set; }
        public string LABEL { get; set; }
        public Nullable<double> PROBCAP { get; set; }
        public Nullable<long> X_SIZE { get; set; }
        public Nullable<long> SD_SIZE { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    }
}
